#!/bin/bash

# URL for ref: https://stackoverflow.com/questions/12082981/get-all-git-commits-since-last-tag?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
# URL for ref: https://git-scm.com/book/en/v2/Git-Basics-Tagging
# GLOBAL HOOKS PATH: https://stackoverflow.com/questions/2293498/applying-a-git-post-commit-hook-to-all-current-and-future-repos?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
# LIST TAGS: https://stackoverflow.com/questions/1064499/how-to-list-all-git-tags?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
# REMOVE TAGS: https://stackoverflow.com/questions/5480258/how-to-delete-a-git-remote-tag?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
# LIST AND SORT TAGS: https://stackoverflow.com/questions/14273531/how-to-sort-git-tags-by-version-string-order-of-form-rc-x-y-z-w?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
# FIRST LINE OF BASH OUTPUT: https://stackoverflow.com/questions/46021955/get-first-line-of-a-shell-command-output?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
# BASH REGEX: https://stackoverflow.com/questions/9597751/using-match-to-find-substrings-in-strings-with-only-bash?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
# RELEASE NAMKNG CONVENTIONS: https://www.drupal.org/node/1015226
# ITERATE THROUGH LINES: https://superuser.com/questions/284187/bash-iterating-over-lines-in-a-variable?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

# STOP MERGE MESSAGE EDITS: https://stackoverflow.com/questions/12752288/git-merge-doesnt-use-default-merge-message-opens-editor-with-default-message?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
# IDEA FOR MERGES: https://www.google.com.au/search?q=git+different+default+merge+commit+messages+for+merge+and+conflict&oq=git+different+default+merge+commit+messages+for+merge+and+conflict&aqs=chrome..69i57j69i64.12928j0j4&sourceid=chrome&ie=UTF-8
# BASH BASIC MATHS: https://askubuntu.com/questions/385528/how-to-increment-a-variable-in-bash?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa





LATEST_MERGE_COMMIT_INFO=$( git log --merges `git describe --tags --abbrev=0`..HEAD --oneline | head -n 1 )


LATEST_MERGE_FROM=$( expr "${LATEST_MERGE_COMMIT_INFO}" : ".* Merge branch '\(.*\)' into .*" )

LATEST_MERGE_TO=$( expr "${LATEST_MERGE_COMMIT_INFO}" : ".* Merge branch .* into \(.*\)" )






echo MERGED FROM: ${LATEST_MERGE_FROM}
echo MERGED TO: ${LATEST_MERGE_TO}

LATEST_TAG=$( git tag -l | sort -V --reverse | head -n 1 )

if [ "${LATEST_MERGE_TO}" == "dev" ]; then
  echo "Merged to dev branch."
  echo "Updating JIRA ticket for ${LATEST_MERGE_FROM}"
elif [ "${LATEST_MERGE_TO}" == "test" ]; then
  echo "Merged to test branch."
  echo "Updating JIRA ticket for ${LATEST_MERGE_FROM}"
  # BUMP VERSION SCRIPT
  source ./bump_version_tag.sh
  # git push

  # NOTE: may need to update this stuff so it gets a new tag. Still needs to be tested if hte line below is enough
  LATEST_TAG=$( git tag -l | sort -V --reverse | head -n 1 )
  # git push -a "${NEW_VERSION_TAG}" -m "Production Release Version: ${LATEST_TAG}"
elif [ "${LATEST_MERGE_TO}" == "master" ]; then
  echo "Merged to master branch."
  echo "Updating JIRA ticket for ${LATEST_MERGE_FROM} to DONE"
  # git push -a "${LATEST_TAG}" -m "Production Release Version: ${LATEST_TAG}"
else
  echo "Error: some other branch"
fi

